export default [
  {
    component: 'CNavItem',
    name: 'Dashboard',
    to: '/dashboard',
    icon: 'cil-speedometer',
  },
  {
    component: 'CNavItem',
    name: 'POS Kasir',
    to: '/pos',
    icon: 'cil-cart',
    roles: ['admin', 'kasir'],
  },
  {
    component: 'CNavTitle',
    name: 'Master Data',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Kategori',
    to: '/categories',
    icon: 'cil-tags',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Master Product',
    to: '/products',
    icon: 'cil-basket',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Report Stock',
    to: '/products/stock-movements',
    icon: 'cil-history',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Report Pendapatan',
    to: '/reports/sales',
    icon: 'cil-dollar',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Supplier',
    to: '/suppliers',
    icon: 'cil-truck',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Penerimaan Barang',
    to: '/goods-receipts',
    icon: 'cil-cloud-download',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Kelola User',
    to: '/users',
    icon: 'cil-people',
    roles: ['admin'],
  },
  {
    component: 'CNavTitle',
    name: 'Master Customer',
    roles: ['admin', 'kasir'],
  },
  {
    component: 'CNavItem',
    name: 'Customer',
    to: '/customers',
    icon: 'cil-people',
    roles: ['admin', 'kasir'],
  },
  {
    component: 'CNavTitle',
    name: 'Pengaturan',
    roles: ['admin'],
  },
  {
    component: 'CNavItem',
    name: 'Upload Logo',
    to: '/settings/logo',
    icon: 'cil-settings',
    roles: ['admin'],
  },
]
